line-length = 125

[lint]
select = ["ALL"]
ignore = [
  "ANN003", # Missing type annotation for **{name}
  "COM812", # Trailing comma missing
  "D100",   # Missing docstring in public module
  "S607",   # Starting a process with a partial executable path
]
